# Generated by Django 3.1.1 on 2020-09-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200912_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='ils',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='n_trees',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='network',
            name='newick_dendroscope_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='output_base',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='network',
            name='population_size',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='network',
            name='n_reticulations',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='n_taxa',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
