# Generated by Django 3.1.1 on 2020-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20200915_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='output_base',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
