# Generated by Django 3.1.1 on 2020-09-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='hybridization_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='n_reticulations',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='n_taxa',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='sites_per_tree',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='speciation_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='time_limit',
            field=models.FloatField(),
        ),
    ]
