# Generated by Django 3.1.1 on 2020-09-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200915_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='ils',
            new_name='incomplete_lineage_sorting',
        ),
    ]
