# Generated by Django 3.1.1 on 2020-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200915_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='trees_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
